title: Phillip Raffnsøe
description: |
  Freelance web designer and developer. Websites, webshops and single page apps.
baseurl: ""
url: "https://praffn.dk"

og_logo: /assets/og_logo.jpg

contact:
  email: phillip@praffn.dk
  phone: '+45 42483410'

markdown:    kramdown

social:
  - github: https://github.com/praffn/
  - linkedin: https://www.linkedin.com/in/praffn/
  - instagram: https://www.instagram.com/praffn.jpg/

collections:
  work:
    output: true

markdown: kramdown

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
  css_class: 'highlight'

plugins:
  # - jekyll-feed
  # - neat
  - sass

navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact

projects:
  - title: ts-static-site
    url: https://github.com/praffn/ts-static-site
    thumbnail: /assets/thumbs/ts-static-site-thumb.jpg
  - title: Ingrid
    url: https://github.com/praffn/ingrid
    thumbnail: /assets/thumbs/ingrid_thumb.jpg
  - title: Bitwise
    url: https://praffn.dk/bitwise/
    thumbnail: /assets/thumbs/bitwise_2.gif
  - title: Flagrant
    url: https://github.com/praffn/Flagrant
    thumbnail: /assets/thumbs/flagrant_thumb.jpg
  - title: btc-cli
    url: https://github.com/praffn/btc
    thumbnail: /assets/thumbs/btc_thumb.gif
  - title: Prat
    url: https://github.com/praffn/prat/
    thumbnail: /assets/thumbs/prat_thumb.jpg