title: Phillip Raffnsøe
baseurl: "" # the subpath of your site, e.g. /blog
url: ""

collections:
  work:
    output: true

markdown: kramdown
plugins:
  # - jekyll-feed
  # - neat
  - sass

projects:
  - title: Bitwise
    url: https://praffn.dk/bitwise/
    thumbnail: /assets/thumbs/bitwise_2.gif
  - title: Ingrid
    url: https://github.com/praffn/ingrid
    thumbnail: /assets/thumbs/ingrid_thumb.jpg
  - title: Bitwise
    url: https://praffn.dk/bitwise/
    thumbnail: /assets/thumbs/bitwise_2.gif

analytics: GTM-KRZ9PRQ